Ignore a GError from printing.
This strange error happens when canceling a "Print to File" operation on
Windows:

Traceback (most recent call last):
  File "zenmapGUI\MainWindow.pyo", line 831, in _print_cb
  File "zenmapGUI\Print.pyo", line 156, in run_print_operation
GError: Error from StartDoc

The web seems mostly silent on this error, and I can't guess at the
cause. Let's ignore the error as it seems to be harmless.

Reported by Imre Adácsi.
http://seclists.org/nmap-dev/2012/q4/161

git-svn-id: https://svn.nmap.org/nmap@30286 e0a8ed71-7df4-0310-8962-fdc924857419